name: smoke

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  check-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "smoke OK ($(date -u +%FT%TZ))"
